name: SSH deployment

on:
  push:
    branches: ["main"]

jobs:
  Unit-Test-API:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
          cache: "pip"
      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt && pip install coverage
      - name: Run tests
        run: python -m coverage run -m pytest
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1

  Deploy-To-Server:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: Build-Docker-Container

    steps:
      - name: Prep for deployment
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo service apache2 stop
            sudo service unseenservant stop
            cp /opt/UnseenServant/CoreServer/config/settings.py ~/settings.backup
            cp /opt/UnseenServant/CoreServer/db.sqlite3 ~/db.backup

      - name: Deploy build
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/UnseenServant
            git fetch
            git checkout origin/main -f
            cp ~/settings.backup CoreServer/config/settings.py
            cp ~/db.backup CoreServer/db.sqlite3

      - name: Resume operations
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            source /opt/UnseenServant/venv/bin/python
            /opt/UnseenServant/CoreServer/manage.py showmigrations
            /opt/UnseenServant/CoreServer/manage.py migrate
            sudo service apache2 start
            sudo service unseenservant start
